version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: cerebro_db
    volumes:
      - C:/cerebro/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
