import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import '@/style/global.scss';
import { ClerkProvider } from '@clerk/nextjs';
import css from './layout.module.scss';
import Navbar from '@/lib/navbar/Navbar';
import React from 'react';
const open_Sans = Open_Sans({ subsets: ['latin'], display: 'swap' });

import { Providers } from '@/app/providers';

export const metadata: Metadata = {
  title: 'Cerebro',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <Providers>
        <html lang="en" className={open_Sans.className}>
          <body className={css.body}>
            <Navbar />
            <div className={css.Layout}>{children}</div>
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
