trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
- group: cerebro-prod
- name: pnpm_config_cache
  value: $(Pipeline.Workspace)/.pnpm-store
- name: artifactName
  value: cerebro_$(Build.BuildId)

stages:
  - stage: Build
    displayName: 'Install | Lint | Build'
    jobs:
      - job: Build
        steps:
          - template: steps/pnpm-build.yml

  - stage: deployprod
    displayName: 'Deploy to Production'
    dependsOn: Build
    jobs:
    - deployment: Prod
      displayName: 'Deploy to Production'
      environment:
        name: prod
        resourceName: nodejs-s-1vcpu-1gb-fra1-01
        resourceType: VirtualMachine
      strategy:
        rolling:
          deploy:
            steps:
              - download: current
                artifact: $(artifactName)
                displayName: 'Download Artifact'

              - script: |
                  rm -r $(FTP_DIST_MONOREPO_DIR) | exit 0
                  mkdir -p $(FTP_DIST_MONOREPO_DIR)
                  tar -xzvf $(Pipeline.Workspace)/$(artifactName)/artifact.tar.gz -C $(FTP_RELEASES_DIR)/$(artifactName)
                displayName: "Create release folder"

              - template: steps/apply-release.yml
                parameters:
                  releasesDir: $(FTP_RELEASES_DIR)
                  releaseName: $(artifactName)

              - script: |
                  cd $(FTP_RELEASES_DIR)
                  ls -td -- */ | tail -n +4 | xargs rm -rf
                displayName: "Cleanup old releases"

  - stage: test
    displayName: 'Run tests'
    jobs:
      - job: test
        steps:
          - script: echo "Run tests"
            displayName: 'Run tests'