trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: steps/pnpm-build.yml
