steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    inputs:
      sources: |
        **/.env.template
      tokenPattern: custom
      tokenPrefix: '{'
      tokenSuffix: '}'
      telemetryOptout: true

    displayName: 'Replace tokens'

  - script: |
      mv apps/server/.env.template apps/server/.env
      mv apps/web/.env.template apps/web/.env
    displayName: 'Rename .env.template files'

  - script: bun lint
    displayName: 'bun run lint'
  - script: bun build
    displayName: 'bun run build'
