name: Switch maintenance

on:
  workflow_dispatch:
    inputs:
      enable_maintenance:
        description: 'Enable maintenance'
        default: true
        required: true
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.enable_maintenance }}"
